---
# tasks file for docker-registry

- name: login
  docker_login:
    #email: "nourelhouda.fdhila@esprit.tn"
    username: "yassinedockeer"
    password: "azeqs.123"
    reauthorize: yes
- name: docker push
  docker_image:
    name: appfront:latest
    repository: yassinedockeer/cd
    push: yes
    source: local 
